import { User, Post, Story, SnapMessage, Community, StoryChain, WeeklyChallenge, NotificationItem } from '@/types/models';

export const SEED_USERS: User[] = [
  {
    id: 'user-kenji',
    username: 'kenji_coder',
    display_name: 'Kenji Sato',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    bio: 'Competitive programmer & mechanical keyboard builder. Training for Black Belt in Code.',
    status_line: 'Debugging Rust concurrency kernels 🦀',
    xp: 5240,
    belt_rank: 'black',
    age: 19,
    is_admin: true,
  },
  {
    id: 'user-maya',
    username: 'maya_ai',
    display_name: 'Maya Lin',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
    bio: 'CS sophomore @ Berkeley. Building agentic social feeds and exploring multimodal diffusion.',
    status_line: 'In library prepping for Midterms 📚',
    xp: 2850,
    belt_rank: 'brown',
    age: 20,
    is_admin: false,
  },
  {
    id: 'user-alex',
    username: 'alex_cyber',
    display_name: 'Alex Vance',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    bio: 'Digital artist, synthwave enthusiast, and indie game dev.',
    status_line: 'Listening to Japanese City Pop 🎧',
    xp: 1420,
    belt_rank: 'blue',
    age: 18,
    is_admin: false,
  },
  {
    id: 'user-elena',
    username: 'elena_sound',
    display_name: 'Elena Rostova',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    bio: 'Ambient producer & tea lover. Let us craft collaborative story chains together.',
    status_line: 'Steeping gyokuro green tea 🍵',
    xp: 850,
    belt_rank: 'green',
    age: 21,
    is_admin: false,
  },
  {
    id: 'user-tariq',
    username: 'tariq_dev',
    display_name: 'Tariq Al-Mansoor',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'Robotics enthusiast and high school tech club president.',
    status_line: 'Soldering ESP32 microcontrollers ⚡',
    xp: 420,
    belt_rank: 'orange',
    age: 17,
    is_admin: false,
  },
  {
    id: 'user-chloe',
    username: 'chloe_art',
    display_name: 'Chloe Dubois',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=300&q=80',
    bio: 'Urban sketching and calligraphy. Exploring minimalist design systems.',
    status_line: 'Sketching Kyoto alleyways 🖌️',
    xp: 210,
    belt_rank: 'yellow',
    age: 19,
    is_admin: false,
  },
  {
    id: 'user-demo',
    username: 'demo_ninja',
    display_name: 'Guest Ninja (You)',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80',
    bio: 'Portfolio evaluator account. Welcome to the NinjaLoop interactive showcase!',
    status_line: 'Testing NinjaLoop portfolio features 🚀',
    xp: 750,
    belt_rank: 'green',
    age: 20,
    is_admin: true,
  }
];

export const SEED_POSTS: Post[] = [
  {
    id: 'post-1',
    author_id: 'user-kenji',
    author: SEED_USERS[0],
    content: 'Just deployed our custom sharding layer for the NinjaLoop realtime stream! Latency dropped under 18ms across all WebSocket regions. Here is the architecture whiteboard.',
    media_urls: ['https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80'],
    mood: 'study',
    privacy: 'public',
    likes_count: 34,
    comments_count: 8,
    has_liked: true,
    is_pinned: true,
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'post-2',
    author_id: 'user-maya',
    author: SEED_USERS[1],
    content: 'Finished round 4 of the campus hackathon! Our agentic assistant just synthesized 40 research papers in under a minute. Anyone want to study together tonight?',
    media_urls: ['https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80'],
    mood: 'creative',
    privacy: 'public',
    likes_count: 52,
    comments_count: 14,
    has_liked: false,
    created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'post-3',
    author_id: 'user-alex',
    author: SEED_USERS[2],
    content: 'Neon reflections after a light rain in Shinjuku. Grabbed this with my 35mm prime lens before hopping on the Yamanote line.',
    media_urls: ['https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80'],
    mood: 'chill',
    privacy: 'public',
    likes_count: 78,
    comments_count: 9,
    has_liked: true,
    created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: 'post-4',
    author_id: 'user-tariq',
    author: SEED_USERS[4],
    content: 'When your code runs with zero errors on the first attempt... wait, why is it passing? That is suspicious 😂',
    mood: 'funny',
    privacy: 'public',
    likes_count: 112,
    comments_count: 22,
    has_liked: false,
    created_at: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
  }
];

export const SEED_STORIES: Story[] = [
  {
    id: 'story-1',
    author_id: 'user-maya',
    author: SEED_USERS[1],
    media_url: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=700&q=80',
    text_overlay: 'Coding marathon in session 💻✨',
    views_count: 48,
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 20 * 3600 * 1000).toISOString(),
  },
  {
    id: 'story-2',
    author_id: 'user-alex',
    author: SEED_USERS[2],
    media_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=700&q=80',
    text_overlay: 'Custom PCB printed! ⚡',
    views_count: 32,
    created_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 16 * 3600 * 1000).toISOString(),
  },
  {
    id: 'story-3',
    author_id: 'user-elena',
    author: SEED_USERS[3],
    media_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=700&q=80',
    text_overlay: 'Morning tea ceremony vibes 🍵',
    views_count: 65,
    created_at: new Date(Date.now() - 11 * 3600 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 13 * 3600 * 1000).toISOString(),
  }
];

export const SEED_COMMUNITIES: Community[] = [
  {
    id: 'comm-1',
    slug: 'tokyo-coders',
    name: 'Tokyo Creative Coders',
    description: 'A community of software engineers, generative artists, and hardware hackers in Tokyo and beyond.',
    avatar_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=300&q=80',
    cover_url: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80',
    creator_id: 'user-kenji',
    rules_text: '1. Be respectful and constructive.\n2. No spam or commercial solicitations.\n3. Share open source repositories with attribution.',
    members_count: 1420,
    is_joined: true,
  },
  {
    id: 'comm-2',
    slug: 'desk-setups',
    name: 'Minimalist Desk Setups',
    description: 'Ergonomic workspaces, custom keycaps, monitor arms, and ambient lighting inspiration.',
    avatar_url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=300&q=80',
    cover_url: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80',
    creator_id: 'user-alex',
    rules_text: '1. Post original workspace pictures.\n2. List gear specs in the comments.',
    members_count: 3890,
    is_joined: false,
  }
];

export const SEED_CHAINS: StoryChain[] = [
  {
    id: 'chain-1',
    title: 'The Whispering Server of Akihabara',
    prompt: 'Underneath an abandoned arcade machine in Akihabara, a glowing green terminal was blinking with an unread root command prompt...',
    creator_id: 'user-kenji',
    creator: SEED_USERS[0],
    status: 'active',
    current_round: 2,
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    nodes: [
      {
        id: 'node-1',
        chain_id: 'chain-1',
        author_id: 'user-kenji',
        author: SEED_USERS[0],
        round_number: 1,
        content: 'Underneath an abandoned arcade machine in Akihabara, a glowing green terminal was blinking with an unread root command prompt.',
        votes_count: 24,
        is_winner: true,
        created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      },
      {
        id: 'node-2',
        chain_id: 'chain-1',
        author_id: 'user-maya',
        author: SEED_USERS[1],
        round_number: 2,
        content: 'Elena brushed away decades of dust, connected her portable cyberdeck, and noticed the incoming packet was originating from the year 2048.',
        votes_count: 19,
        has_voted: true,
        is_winner: false,
        created_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
      },
      {
        id: 'node-3',
        chain_id: 'chain-1',
        author_id: 'user-alex',
        author: SEED_USERS[2],
        round_number: 2,
        content: 'A synthetic voice crackled from the coin return chute: "Welcome back, Operator Zero. Initiate the backup protocol before midnight."',
        votes_count: 15,
        has_voted: false,
        is_winner: false,
        created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
      }
    ]
  }
];

export const SEED_CHALLENGES: WeeklyChallenge[] = [
  {
    id: 'chal-1',
    title: 'Show Your Study & Desk Setup',
    prompt: 'Capture your workspace, mechanical keyboard, or study nook where you hone your craft. Include your favorite productivity tool!',
    theme_tag: 'desk-setup',
    starts_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    ends_at: new Date(Date.now() + 4 * 24 * 3600 * 1000).toISOString(),
    is_active: true,
    submissions_count: 64,
  }
];
